server:
  http:
    network: tcp
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    network: tcp
    addr: 0.0.0.0:9000
    timeout: 1s
  domain: https://rohitShort.com
  default_expiry_hours: 24
data:
  database:
    driver: postgres
    source: host=localhost port=5432 user=postgres password=postgres dbname=url_shortener sslmode=disable
  redis:
    network: tcp
    addr: localhost:6379
    password: ""
    db: 0
    dial_timeout: 1s
    read_timeout: 0.5s
    write_timeout: 0.5s
