server:
  http:
    addr: 0.0.0.0:8000
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 5s
  domain: https://rohitShort.com
  default_expiry_hours: 24
data:
  database:
    driver: postgres
    source: postgres://postgres:postgres@localhost:5432/urlshortener?sslmode=disable
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
